dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
env:
  global:
  - secure: CUnu2D4uF8SyCui96qQeppFOBdFwacjDPXPZuwMbk+nmyVv8NWU0Qo452tzbLmBML3KQFRzzSThZ6/8qFjOVKY6T7Kzl/lRNtMPIjca4IOJ8iqtgkFhb5vmZd/uS2Axm5d6Bo/9BoBHiv0ZlCPrakauaP0wEI3txboSJW/uTxKdc9QCJ23Ey/0KxLdjl4nZhyVznEWE2Mac157ge3B78dLVS/ii4k8SD1HM1idCq5lR2I133V1YBQe+oCaMtbni3e8Fkj0qtqtI8C5wIv610N8uxeKoqNXX+q/USWQD1xw5cfV6pJtU1nYDiSl4/nX1bUM/rBfYsikhhL18w9L5rZyiIZdX+kpJ1hwA+2sjplHWxqLUk7CzEYzRUukGJ3ENjg2Z6yZWJGxUnwrfWUkPg3x6UwVKwJ3m2PZL2lxjW0nyeOFtKPnYTPioUDr55FafCJVsSshsvs9x/oFrMHh/rZPdnON11pmiZfVxONTTg/u+zUlGejs4LOuVg+8TC7HB7lJiXVFadaRriiFu+xpivCK/hLLa8InGMRhw8eryZI2itL+jm2Q5YJRgYnem8c8tOEoQxGqvaRfS6r+fVMS9QoRtfVswfp8XkIryBkWKS+7BD1i0D0J4AT/xNx+7BhJRYKdP7pLYGHNYbR3Yr8x6W3HjYtYj0Xog+pB3xFnfEpEA=
  - secure: quBlPf2M4BGNwGxyoo0YEn1yaZN5Per4i0Tn6rn0feAYTyOn/oVOvfR1hGeVODnh+ah2Fqkxw3DHUYcO6ooWfeAKPWCZRKuOt2x68BqWIMR/wetl+t/CLJZ2NnFq+7jP4v8jwngSIH3MjsAd5BZoBeYp16vmoAUbrhmdemDmJVXXhEO1UNzv/AI1NWTrJNoBCvkhubqqLRG3E20OPZu57FGVRcwm+kfTKINCFpt/C5gxKgQQRhJxzZdax9j1HJx4C1884CI3rq9gJXS0KBeg5mOGTxQP4iyg/ynb/V0O+Hw9LC+6m/NIKJDxFEeYvDUQqVwvWaK1ZXxAv5HVWK8iEyc2+xP6gf9OBOFxLqHJsINT59p8x/CJwHwYN6pAXev8hanN/tTZHatwZUvjywZfFCC72PB7SIuxH9Ni5XHVC0R9rMP/SbKZRjDehKylbouH6Dbk/e8Jg+itbKC15O+4f/Wnmm0AaJLnP4uTnyZfzRMx5FsLBvRSqIaG43QDd33ykO1db7c+VDdTsjw7u0PMdHvZKB9uAT+9cBJ9b3fKJZlv83GmzerA0uCjT2cQml5zeFPBTaVu1QDillTTiuQoy0isTNx/WVRP1K5iP8A/z6ig2tj1y9Pitc4ZQKz638QEtju+NwsdRw1rPKE9UYshXpNORo45TzauuyaI7uxzp6s=
