dist: trusty
addons:
  chrome: stable
  sauce_connect: true
language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
env:
  global:
  - secure: SWDqAygJCgoXsMaw6G/pDt+dMMy8djmT0XQPn8/jzWY5RKl8OCtnsXn6esqAsdV47R0Kc8Xz6gkwYk4O6xCKga+zHemd8CzNRsEpXx7/aa2CVFH4aNDAQ6Xm4AqbyhNXKwxJn4d4cTuBl9q/TbWvJe0kGUAfszJTv8lK4v/KboWAvIQV2H0QhxvPDImTeHF8sHOe9xEek7cJZVIFgRwEJqmSWyofA3EXq7rV62m/8y7ip4qDvmUw6B3xobU+2tGGA+bg7C2O/9ZHo6bf44KKusyD5SEVGjhKziUWejbF6Q+Fhfq7GtlkAF+PgyJI/2QYhacpWNnZMCBMXN3/oiu45Sb6oUxQbHYAIg3dQgrjDGK2onPxoFqAJebHv3+vbpJ3B6rR0DU6g7vbVQTq6e07nFmW55wgI3eet7kJ/triDa0FDhS0AO2+TL81Fbi+Y7oDga/MhsnTfBR/XnJKj/LSLu6z9MgiYHLYZwCTgfFKlZi6xMWTE+gxkWZaPblbjjvL1/oQbeZFlV5rB/hhYFinWFGaYnEIjkWj/d7J26BhCmWoIKFuz5rbdPNJ7Y2m8xQxDNAkHPXAsuJ3Vj1/mLY+uQPGxbbLqmYSID9GzYTBkTiCWP1uh0nPYge3zoKopYLnj3aDi8PKFLLhHnIIsahD/E/T2lHnUj8narnWRFveG7I=
  - secure: sllnB+RR+HJryzAhdMoBJNUyEQhy2ctIr21SWJcsUtnnVj/fkJ9muQ/tfuIG4jkp5o5t9H/nUfFT3V4FcRUfUIftSdxlR+tN+fq4ee2J7kariZER0eiYY3EOdqxHfzLV91iYzkVn6UYk36M+M0tKlmMm3heN/19dJvQ4kS7/J1aumwpbjManbKIo9PpQuML3L9xjvIFI0mkh8Pounf4V93gstR9bRnjYjBo/OGx+C2niNAei5r3h2vHTPYRgIWJ8j1bUZVexpdCcWc5k9QsF3rHs1uvPaFM80MeoRz2GMAbUexpXwQqIQI+YhkZY6JF43o6Wvh3GusfDzjiUQ7bb2BVz5faO8frn0QEZjueGv+Y877mAnDAvQ03LaiUFePiAdshL4B82fZOQNh9KD+4znfocpmXpsHm6ANr40wY06eGQBqb0dPMAhNC3lWaNBahM5HIOsU0+goz8Z7hc+Y4+IQFqLfDDJzp6ChsfH+1C5G0WltnevIf5Af3j0J80/hbsfovfijro2rlkS5oemHZ97yKzPRGr264a0jrMchukcIJ8QaRX7kKidR+VJiQm3Wgpdn3G9Xy/CNLLWM/ZjT4Z+FOKGvGif9LfTHbZvARxbPTpz0Z+2nyrgKjdWGo4JM1TU4scvtXtSBoPLwHBeRkIshoFLDfRhD0eB94UIZT8DnI=
