dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
secure: "f9vLueE/PesQaVgB6PEhU8DEOoKy8+pCzL+E/iVBJJo59jUBXnMZrzJh9gDRKvW05O0yXSgXz5r4IsXPL0xWvVkA1AmPzOHEmoDABOc5TxcUot7bgruYE810v4jG8NaDOEKcGyGMuTn8H+SaydDjBIsXqQgSkJIHctUnyoCIXrgqbm6YUheBJLh4gMZfB/oR5joNu0CNifJwiV9L0OlzNnIZsg2eepbxi667WxPCNvr1tHd/jYTmda585Idw1vmHj4xuUWRfcMsNTk/IoxqdR5fMWnk1AtURhq8zIFMfdKpiYMBoSwszYq9RxPzAovDlUG81P/WIY+jKBB8XvGLfH1UOyOUL8CfDshoP0wkeIS6CfUpjpXcwkarLKuBnZa/Sm1dRXdOI4StP5UCD7zhIVW5Jay+vg2hng3sny/lhHyqmOI5A9qFt3Up5FbDtfO3+U9hDY6YbZp/olOhZYfiyiiqlKW20Rug8ccjatJKOZt0BUZ3Y3dRJXxYKnOpFgciv2WUT7qrZZXaCglESzeemeWmuromeG1SMEnefgt2MdEFW/lQBVYWIfJnDYdjq0VerAgBxJczX5IO0FizfPygRt5BrlbOszjNMa6va5tWYngd03cSoyuEsbZpukXHAspjA9FpH7FDbLNgX37L5Dst8/2Dvj9IZNgsAVyFzeKnFUI0="
