dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
env:
  global:
  - secure: HN9h51hb74/A7Qt1WHbxNgyV1fhnFgHMgvLll91u7MfTd5tY0x/dOBDItXqxYpPZ0U//SCpLf1tGveA5YXWeL2E1+EUz4tWftijlhJox2RdwOn2dBJTQ4XND6/lB5vIItlZdCc/zrEypp5ziFaiMauwQZLWZHw7QRc2UgrpHI26m4IrLgFaAcI5YA+Ab3Iwe5/RjWl49TiyZSBc2T2V3P14AhkAv52xpCaTbH1gsmokku3AWvG9PmRRAunLNigYaMgDYVpeh+zM8BLs24C8NAAO4/JRpbjmvQzFi79/gshoQw9ka2iadJ/DcqNB6SM3qG2kQXH8hc25vbxakrJ6wJ9R2S0im72yQgsUGuG7/VzR0oV+PCkZRI7bXurJJvde9PQtUusyXI72xY5jEjzpIA2eBPT4fyMEZcJCAGPYsBRiTC9mYAlY+ABirTIsveC2bG4uGG0cNxmYdJ1++4WvWC05YRQWBZPOjTqy8SpBPgeUEn/hXUbJ9qnPHXfC3fxVnJ6Oo4VmGLik0DRypE3bKSgl8evIYtdY9Tg+BRDHSR1ZsRtuF9aWZ1bV1yipxuOHvG/srKX66CiOVLBFMXOR5JAVOUBC33BRstQemGXz8Gm6+sd6EN36t5PolvyTfEukETXi1JVmilWcG6JmZ3tWCy4AMXEHlry4XsNed8MlWars=
  - secure: T0eciL2fxQ9S6tYYeGPusNQfpIU+QJWg2bsaZQA8fhlk0O32Slt09O7hATEaZoKRTVVFrgqCEBECLx9bM/b3Fdz97efm7R0b10MFx1k0EpwPTgxH/TgIfR8c/4nDYRInQ6nhd7DeFMKZlGqD20QFXnl5u/l0Eh6ywKv072iSiPHWV/UfkRBVokHF+PhQ+pabxjoVoujkUkLTl7/v1cLEsPpqyK6E85iiHsH+VMvlnGtZURKgvuHc4Pczkxz6RGY5t5Uw1VewuHZMXjGpmUpKXx0A10YzSiy6DHU53X0sZEhOZvaHWC6sExdN/7FGFqZI0V72EMbv0nJhik4OUdSMF9i6nW47xvhGxbtsAy2uvMABTNqP/OQEkzmy4iHIKRhmHdf4OswXpICI66rdZeBfClyClkN1mxNXghdtwlaYwZvZytv5CX+zRjSNoduPtCV37MA/K6GRA5PVjoALVoIriWMKQhnYCqUTR73gCQPK8cIzqoBLGyQUXNSexNNQhQrfX5rfFGpfkid6L/MYn5hGX64CPODBZxNfsGXPnSE+TzqLt4oK4As263C0tAg9cH/1h7Yh7OBJBInooGueaYHBh5mtP5J6xoArao/VmeeBSOV8PkCw2m9+bCtT8UP8M/obcNy3gRblRaMy1WyA50lrCoB/mZRJuyweRezymZyymjw=
